language: scala

scala:
  - 2.11.11
  - 2.12.2

sudo: false

jdk:
  - oraclejdk8

env:
  - TRAVIS_NODE_VERSION="8.1.4"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaJsTestkitJS/test:fastOptJS
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaJsTestkitJS/test
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaActorTestJS/test:fastOptJS
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaActorTestJS/test
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaJsStreamTestkitJS/test:fastOptJS
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaJsStreamTestkitJS/test
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaStreamTestJS/test:fastOptJS
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaStreamTestJS/test
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
